### ISSUE TITLE
Maps example: leaflet polylines do not render correctly

### ISSUE THREAD

**Issue by rtholmes** [blackberry/BB10-WebWorks-Samples#136]
In extending the Maps sample I found a leaflet rendering problem with polylines that the Leaflet team has closed as a BB10 issue:

https://github.com/Leaflet/Leaflet/issues/1640

From the original bug, polylines look like this on the Dev Alpha C:

![image](https://f.cloud.github.com/assets/89003/459317/73d92c4a-b3fe-11e2-994a-a25b0a4b9021.png)

**Comment by timwindsor** [comment]
This type of issue should really go in the developer issue tracker rather than Github. But that said, I don't think it's an issue with newer software builds. What version are you running on your Dev Alpha C? I'm on 10.1.0.1609 on my Q10 and the polygon in the getting started example appears correctly.
