### ISSUE TITLE
should I use this project or cordova?

### ISSUE THREAD

**Issue by arasbm** [blackberry/BB10-WebWorks-Samples#195]
I already have apps build using cordova. Recently I tried adding blackberry10 platform as per customer request. I got a lot of very unhelpful errors, I will open another ticket for that. But I am mostly wondering why BB is working on a separate project instead of just contributing to the cordova blackberry10 platform and making sure it works?

**Comment by timwindsor** [comment]
That's exactly what we've done here. We wrote the code for Cordova so that it would work for BlackBerry 10, and we ported all our core APIs over. WebWorks 2.0 is literally just Cordova with some extras to make it easier for traditional BlackBerry developers to get started with. If you're main focus is cross platform, and you've already got projects setup with Cordova, then I would not tell you to switch.

I'll take a look at your other issue and see what I can help with.

**Comment by arasbm** [comment]
Thank you for the quick response. Honestly I got very scared when I saw this project was linked on blackberry website. It is good to hear you are staying close to cordova. I am getting sick of all the native mobile platforms, there is literally more than 10GB of crap collected on my development machine for all the different platforms. Sometime I wonder why I need all of this just to write a web app. But honestly, it is very good to hear BB is realizing this and moving toward adopting web as a platform.

Thanks for your quick response about my problem, I will get back to you there (#196) with some more debug info. Please feel free to close this rant/issue. Cheers!
