### ISSUE TITLE
pushCaptureBasics code issues:

### ISSUE THREAD

**Issue by miamon** [blackberry/BB10-WebWorks-Samples#212]
On **pushClient.js**

**Line 38 appears**:

```
'ppgUrl': 'http://cp@@@@.pushapi.eval.blackberry.com'
```

correct is:

```
'ppgUrl': 'http://pushapi.eval.blackberry.com'
```

**Line 196 appears**:

```
if (pushClient.PushService) {
```

correct is:

```
if (pushClient.pushService) {
```

**Comment by miamon** [comment]
And a doubt:

it's not better move Listen for invoke requests inside 'deviceready'

```
                /* Wait for deviceready before leveraging blackberry APIs. */
                document.addEventListener('deviceready', function ondeviceready() {
                    /* Listen for invoke requests. */
                    document.addEventListener('invoked', pushClient.onInvoke);

                    /* Initialize our Push Initiator. */
                    pushInitiator.init();

                }, false);
```

**Comment by timwindsor** [comment]
@oros Can you take a look at this, Eric?

**Comment by oros** [comment]
@miamon Great feedback, very much appreciated.

**Line 38**
Can actually be either of the proposed URLs. The URL with the cp@@@@ prefix helps identify your application to the push servers. Should there ever be any issues, those pushes can be looked into. Technically both should work.

**Line 196**
You are correct. Furthermore, likely best to change this to **pushClient.pushService !== 0** since we are initializing the value. I'm actually quite surprised this didn't come up in my testing...

**invoked Listener**
Correct again. Since the **invoked** callback itself leverages **blackberry** APIs, it would be safer to move this inside the **deviceready** callback. The original call itself shouldn't fail, but should an invocation occur after **load** and before **deviceready**, there could be some issues.

I'll submit the above changes shortly.

**Comment by oros** [comment]
Pull request submitted:
https://github.com/blackberry/BB10-WebWorks-Samples/pull/213
