### ISSUE TITLE
PushCapture example missing webworks script

### ISSUE THREAD

**Issue by diogogmt** [blackberry/BB10-WebWorks-Samples#7]
The pushCapture example is trying to load a file that doesn't exist.

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:9910/pushCapture/Scripts/webworks-1.0.1.8.js

**Comment by mdandrea** [comment]
Hi Diogo,

All of the BB10 WebWorks samples actually do not include the WebWorks JS script.
This is so that you can copy over and point to the one included in the version of the WebWorks SDK that you download.

See the "How to Build" section of the Push Capture sample app for more info on the steps to get the sample up and running.

Let me know if you run into any issues or have any questions.

Thanks,

Matt
